import type { RadiologyGroup, RadiologyPriority, RadiologyResultBlock, RadiologySummaryRow, RadiologyTest } from "./types";

export const radiologyTestList: RadiologyTest[] = [
  { id: "ct-ct-head-brain-plain", name: "CT Head / Brain - Plain", description: "Head", modality: "CT", category: "CT Scan", code: "CT-001", specifications: ["Head"] },
  { id: "ct-ct-head-brain-contrast", name: "CT Head / Brain - Contrast", description: "Head", modality: "CT", category: "CT Scan", code: "CT-002", specifications: ["Head", "Contrast"] },
  { id: "ct-ct-pns-face-orbit", name: "CT PNS / Face / Orbit", description: "Head/Face", modality: "CT", category: "CT Scan", code: "CT-003", specifications: ["Head/Face", "Optional"] },
  { id: "ct-ct-neck", name: "CT Neck", description: "Neck", modality: "CT", category: "CT Scan", code: "CT-004", specifications: ["Neck", "Optional"] },
  { id: "ct-ct-chest-thorax", name: "CT Chest / Thorax", description: "Chest", modality: "CT", category: "CT Scan", code: "CT-005", specifications: ["Chest", "Optional"] },
  { id: "ct-ct-abdomen-pelvis", name: "CT Abdomen & Pelvis", description: "Abdomen/Pelvis", modality: "CT", category: "CT Scan", code: "CT-006", specifications: ["Abdomen/Pelvis", "Optional"] },
  { id: "ct-ct-kub-stone-protocol", name: "CT KUB (Stone protocol)", description: "Renal", modality: "CT", category: "CT Scan", code: "CT-007", specifications: ["Renal"] },
  { id: "ct-ct-spine-cervical-dorsal-lumbar", name: "CT Spine (Cervical/Dorsal/Lumbar)", description: "Spine", modality: "CT", category: "CT Scan", code: "CT-008", specifications: ["Spine", "Optional"] },
  { id: "ct-ct-angiography-head-neck-pulmonary-aorta-peripheral", name: "CT Angiography (Head / Neck / Pulmonary / Aorta / Peripheral)", description: "Vascular", modality: "CT", category: "CT Scan", code: "CT-009", specifications: ["Vascular", "Contrast"] },
  { id: "ct-ct-pulmonary-angiography-ctpa-pe-protocol", name: "CT Pulmonary Angiography (CTPA - PE protocol)", description: "Chest vascular", modality: "CT", category: "CT Scan", code: "CT-010", specifications: ["Chest vascular", "Contrast"] },
  { id: "ct-hrct-chest-high-resolution", name: "HRCT Chest (High Resolution)", description: "Chest", modality: "CT", category: "CT Scan", code: "CT-011", specifications: ["Chest"] },
  { id: "ct-ct-urography-ctu", name: "CT Urography (CTU)", description: "Renal", modality: "CT", category: "CT Scan", code: "CT-012", specifications: ["Renal", "Contrast"] },
  { id: "ct-ct-extremity-joint", name: "CT Extremity / Joint", description: "Extremity", modality: "CT", category: "CT Scan", code: "CT-013", specifications: ["Extremity", "Optional"] },
  { id: "ct-ct-whole-body-polytrauma-protocol", name: "CT Whole Body (Polytrauma protocol)", description: "Whole body", modality: "CT", category: "CT Scan", code: "CT-014", specifications: ["Whole body", "Contrast"] },
  { id: "ct-ct-coronary-angiography-calcium-score", name: "CT Coronary Angiography / Calcium Score", description: "Cardiac", modality: "CT", category: "CT Scan", code: "CT-015", specifications: ["Cardiac", "Contrast"] },
  { id: "usg-usg-abdomen-whole", name: "USG Abdomen (Whole)", description: "Abdomen", modality: "Ultrasound", category: "Ultrasound", code: "USG-001", specifications: ["Abdomen"] },
  { id: "usg-usg-abdomen-pelvis", name: "USG Abdomen & Pelvis", description: "Abdomen/Pelvis", modality: "Ultrasound", category: "Ultrasound", code: "USG-002", specifications: ["Abdomen/Pelvis"] },
  { id: "usg-usg-kub-kidney-ureter-bladder", name: "USG KUB (Kidney-Ureter-Bladder)", description: "Renal", modality: "Ultrasound", category: "Ultrasound", code: "USG-003", specifications: ["Renal"] },
  { id: "usg-usg-pelvis-female", name: "USG Pelvis (female)", description: "Pelvis", modality: "Ultrasound", category: "Ultrasound", code: "USG-004", specifications: ["Pelvis"] },
  { id: "usg-usg-obstetric-early-anomaly-growth", name: "USG Obstetric (Early / Anomaly / Growth)", description: "Obstetric", modality: "Ultrasound", category: "Ultrasound", code: "USG-005", specifications: ["Obstetric"] },
  { id: "usg-usg-tvs-transvaginal", name: "USG TVS (Transvaginal)", description: "Pelvis", modality: "Ultrasound", category: "Ultrasound", code: "USG-006", specifications: ["Pelvis"] },
  { id: "usg-usg-scrotum-testis", name: "USG Scrotum / Testis", description: "Scrotum", modality: "Ultrasound", category: "Ultrasound", code: "USG-007", specifications: ["Scrotum"] },
  { id: "usg-usg-thyroid-neck", name: "USG Thyroid / Neck", description: "Neck", modality: "Ultrasound", category: "Ultrasound", code: "USG-008", specifications: ["Neck"] },
  { id: "usg-usg-breast", name: "USG Breast", description: "Breast", modality: "Ultrasound", category: "Ultrasound", code: "USG-009", specifications: ["Breast"] },
  { id: "usg-usg-soft-tissue-local-part", name: "USG Soft Tissue / Local part", description: "As specified", modality: "Ultrasound", category: "Ultrasound", code: "USG-010", specifications: ["As specified"] },
  { id: "usg-fast-scan-trauma-focused", name: "FAST scan (trauma - focused)", description: "Abdomen/Chest", modality: "Ultrasound", category: "Ultrasound", code: "USG-011", specifications: ["Abdomen/Chest"] },
  { id: "usg-doppler-carotid-vertebral", name: "Doppler - Carotid / Vertebral", description: "Neck vessels", modality: "Ultrasound", category: "Ultrasound", code: "USG-012", specifications: ["Neck vessels"] },
  { id: "usg-doppler-peripheral-arterial-limb", name: "Doppler - Peripheral Arterial (Limb)", description: "Extremity vessels", modality: "Ultrasound", category: "Ultrasound", code: "USG-013", specifications: ["Extremity vessels"] },
  { id: "usg-doppler-venous-dvt-study-limb", name: "Doppler - Venous / DVT study (Limb)", description: "Extremity veins", modality: "Ultrasound", category: "Ultrasound", code: "USG-014", specifications: ["Extremity veins"] },
  { id: "usg-doppler-renal-portal-abdominal", name: "Doppler - Renal / Portal / Abdominal", description: "Abdomen vessels", modality: "Ultrasound", category: "Ultrasound", code: "USG-015", specifications: ["Abdomen vessels"] },
  { id: "usg-doppler-obstetric-fetal-umbilical", name: "Doppler - Obstetric (fetal/umbilical)", description: "Obstetric", modality: "Ultrasound", category: "Ultrasound", code: "USG-016", specifications: ["Obstetric"] },
  { id: "usg-echocardiography-2d-doppler", name: "Echocardiography 2D + Doppler", description: "Cardiac", modality: "Ultrasound", category: "Ultrasound", code: "USG-017", specifications: ["Cardiac"] },
  { id: "usg-usg-guided-procedure-aspiration-marking", name: "USG-guided procedure (aspiration/marking)", description: "As specified", modality: "Ultrasound", category: "Ultrasound", code: "USG-018", specifications: ["As specified"] },
  { id: "mri-mri-brain-plain", name: "MRI Brain - Plain", description: "Head", modality: "MRI", category: "MRI", code: "MRI-001", specifications: ["Head"] },
  { id: "mri-mri-brain-contrast-gadolinium", name: "MRI Brain - Contrast (Gadolinium)", description: "Head", modality: "MRI", category: "MRI", code: "MRI-002", specifications: ["Head", "Contrast"] },
  { id: "mri-mri-brain-with-mra-mrv", name: "MRI Brain with MRA / MRV", description: "Head vascular", modality: "MRI", category: "MRI", code: "MRI-003", specifications: ["Head vascular", "Optional"] },
  { id: "mri-mri-spine-cervical-dorsal-lumbar-whole", name: "MRI Spine (Cervical/Dorsal/Lumbar/Whole)", description: "Spine", modality: "MRI", category: "MRI", code: "MRI-004", specifications: ["Spine", "Optional"] },
  { id: "mri-mri-screening-spine-whole", name: "MRI Screening Spine (whole)", description: "Spine", modality: "MRI", category: "MRI", code: "MRI-005", specifications: ["Spine"] },
  { id: "mri-mri-abdomen", name: "MRI Abdomen", description: "Abdomen", modality: "MRI", category: "MRI", code: "MRI-006", specifications: ["Abdomen", "Optional"] },
  { id: "mri-mrcp-cholangio-pancreatography", name: "MRCP (Cholangio-pancreatography)", description: "HBP", modality: "MRI", category: "MRI", code: "MRI-007", specifications: ["HBP"] },
  { id: "mri-mri-pelvis", name: "MRI Pelvis", description: "Pelvis", modality: "MRI", category: "MRI", code: "MRI-008", specifications: ["Pelvis", "Optional"] },
  { id: "mri-mri-joint-extremity-knee-shoulder-hip-etc", name: "MRI Joint / Extremity (Knee/Shoulder/Hip/etc.)", description: "Extremity", modality: "MRI", category: "MRI", code: "MRI-009", specifications: ["Extremity", "Optional"] },
  { id: "mri-mri-angiography-mra-venography-mrv", name: "MRI Angiography (MRA) / Venography (MRV)", description: "Vascular", modality: "MRI", category: "MRI", code: "MRI-010", specifications: ["Vascular", "Optional"] },
  { id: "mri-mri-breast", name: "MRI Breast", description: "Breast", modality: "MRI", category: "MRI", code: "MRI-011", specifications: ["Breast", "Contrast"] },
  { id: "mri-functional-dti-spectroscopy-advanced", name: "Functional / DTI / Spectroscopy (advanced)", description: "Head", modality: "MRI", category: "MRI", code: "MRI-012", specifications: ["Head", "Optional"] },
  { id: "mri-mri-cardiac", name: "MRI Cardiac", description: "Cardiac", modality: "MRI", category: "MRI", code: "MRI-013", specifications: ["Cardiac", "Contrast"] },
  { id: "xray-x-ray-chest-pa-ap", name: "X-Ray Chest PA / AP", description: "Chest", modality: "X-Ray", category: "X-Ray", code: "XRAY-001", specifications: ["Chest"] },
  { id: "xray-x-ray-chest-lateral", name: "X-Ray Chest Lateral", description: "Chest", modality: "X-Ray", category: "X-Ray", code: "XRAY-002", specifications: ["Chest"] },
  { id: "xray-x-ray-pns-paranasal-sinuses", name: "X-Ray PNS (Paranasal Sinuses)", description: "Head/Face", modality: "X-Ray", category: "X-Ray", code: "XRAY-003", specifications: ["Head/Face"] },
  { id: "xray-x-ray-skull-ap-lateral", name: "X-Ray Skull AP / Lateral", description: "Head", modality: "X-Ray", category: "X-Ray", code: "XRAY-004", specifications: ["Head"] },
  { id: "xray-x-ray-cervical-spine-ap-lat", name: "X-Ray Cervical Spine AP / Lat", description: "Spine", modality: "X-Ray", category: "X-Ray", code: "XRAY-005", specifications: ["Spine"] },
  { id: "xray-x-ray-dorsal-lumbar-ls-spine", name: "X-Ray Dorsal / Lumbar / LS Spine", description: "Spine", modality: "X-Ray", category: "X-Ray", code: "XRAY-006", specifications: ["Spine"] },
  { id: "xray-x-ray-pelvis-ap", name: "X-Ray Pelvis AP", description: "Pelvis", modality: "X-Ray", category: "X-Ray", code: "XRAY-007", specifications: ["Pelvis"] },
  { id: "xray-x-ray-abdomen-erect-supine-kub", name: "X-Ray Abdomen Erect / Supine (KUB)", description: "Abdomen", modality: "X-Ray", category: "X-Ray", code: "XRAY-008", specifications: ["Abdomen"] },
  { id: "xray-x-ray-upper-limb-shoulder-arm-elbow-forearm-wrist-hand", name: "X-Ray Upper Limb (Shoulder/Arm/Elbow/Forearm/Wrist/Hand)", description: "Extremity", modality: "X-Ray", category: "X-Ray", code: "XRAY-009", specifications: ["Extremity"] },
  { id: "xray-x-ray-lower-limb-hip-thigh-knee-leg-ankle-foot", name: "X-Ray Lower Limb (Hip/Thigh/Knee/Leg/Ankle/Foot)", description: "Extremity", modality: "X-Ray", category: "X-Ray", code: "XRAY-010", specifications: ["Extremity"] },
  { id: "xray-x-ray-ribs-sternum", name: "X-Ray Ribs / Sternum", description: "Chest wall", modality: "X-Ray", category: "X-Ray", code: "XRAY-011", specifications: ["Chest wall"] },
  { id: "xray-portable-bedside-x-ray-icu-er", name: "Portable / Bedside X-Ray (ICU/ER)", description: "As specified", modality: "X-Ray", category: "X-Ray", code: "XRAY-012", specifications: ["As specified"] },
  { id: "xray-x-ray-abdomen-for-acute-abdomen-series", name: "X-Ray Abdomen for Acute Abdomen series", description: "Abdomen", modality: "X-Ray", category: "X-Ray", code: "XRAY-013", specifications: ["Abdomen"] },
  { id: "mammo-mammography-bilateral-screening", name: "Mammography Bilateral (Screening)", description: "Breast", modality: "Mammography", category: "Mammography", code: "MAMMO-001", specifications: ["Breast"] },
  { id: "mammo-mammography-diagnostic-unilateral-bilateral", name: "Mammography Diagnostic (Unilateral/Bilateral)", description: "Breast", modality: "Mammography", category: "Mammography", code: "MAMMO-002", specifications: ["Breast"] },
  { id: "mammo-mammography-with-tomosynthesis-3d", name: "Mammography with Tomosynthesis (3D)", description: "Breast", modality: "Mammography", category: "Mammography", code: "MAMMO-003", specifications: ["Breast"] },
  { id: "mammo-stereotactic-mammography-guided-biopsy", name: "Stereotactic / Mammography-guided biopsy", description: "Breast", modality: "Mammography", category: "Mammography", code: "MAMMO-004", specifications: ["Breast"] },
  { id: "fluoro-barium-swallow", name: "Barium Swallow", description: "Upper GI", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-001", specifications: ["Upper GI", "Contrast"] },
  { id: "fluoro-barium-meal-meal-follow-through", name: "Barium Meal / Meal Follow-through", description: "Upper GI", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-002", specifications: ["Upper GI", "Contrast"] },
  { id: "fluoro-barium-enema", name: "Barium Enema", description: "Lower GI", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-003", specifications: ["Lower GI", "Contrast"] },
  { id: "fluoro-ivp-ivu-intravenous-urography", name: "IVP / IVU (Intravenous Urography)", description: "Renal", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-004", specifications: ["Renal", "Contrast"] },
  { id: "fluoro-mcu-rgu-micturating-retrograde-urethrogram", name: "MCU / RGU (Micturating / Retrograde Urethrogram)", description: "Urinary", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-005", specifications: ["Urinary", "Contrast"] },
  { id: "fluoro-hsg-hysterosalpingography", name: "HSG (Hysterosalpingography)", description: "Pelvis", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-006", specifications: ["Pelvis", "Contrast"] },
  { id: "fluoro-sinogram-fistulogram", name: "Sinogram / Fistulogram", description: "As specified", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-007", specifications: ["As specified", "Contrast"] },
  { id: "fluoro-t-tube-contrast-study", name: "T-tube / Contrast study", description: "As specified", modality: "Fluoroscopy", category: "Fluoroscopy & Contrast Studies", code: "FLUORO-008", specifications: ["As specified", "Contrast"] },
  { id: "ir-usg-ct-guided-biopsy-fnac-core", name: "USG / CT-guided Biopsy (FNAC / core)", description: "As specified", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-001", specifications: ["As specified", "Optional"] },
  { id: "ir-usg-ct-guided-aspiration-drainage-pigtail", name: "USG / CT-guided Aspiration / Drainage (pigtail)", description: "As specified", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-002", specifications: ["As specified"] },
  { id: "ir-angiography-diagnostic-dsa", name: "Angiography (Diagnostic - DSA)", description: "Vascular", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-003", specifications: ["Vascular", "Contrast"] },
  { id: "ir-angioplasty-stenting", name: "Angioplasty / Stenting", description: "Vascular", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-004", specifications: ["Vascular", "Contrast"] },
  { id: "ir-embolization-bleed-tumour-uterine", name: "Embolization (bleed / tumour / uterine)", description: "Vascular", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-005", specifications: ["Vascular", "Contrast"] },
  { id: "ir-central-line-picc-insertion-image-guided", name: "Central Line / PICC insertion (image-guided)", description: "Vascular access", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-006", specifications: ["Vascular access"] },
  { id: "ir-nephrostomy-biliary-drainage-pcn-ptbd", name: "Nephrostomy / Biliary drainage (PCN/PTBD)", description: "Renal/Biliary", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-007", specifications: ["Renal/Biliary", "Contrast"] },
  { id: "ir-rf-ablation-tace-tumour", name: "RF Ablation / TACE (tumour)", description: "As specified", modality: "Interventional Radiology", category: "Interventional Radiology", code: "IR-008", specifications: ["As specified", "Contrast"] },
  { id: "nuclear-bone-scan-whole-body", name: "Bone Scan (Whole body)", description: "Whole body", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-001", specifications: ["Whole body", "Radiotracer"] },
  { id: "nuclear-thyroid-scan-uptake", name: "Thyroid Scan / Uptake", description: "Neck", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-002", specifications: ["Neck", "Radiotracer"] },
  { id: "nuclear-renal-scan-dtpa-dmsa-mag3", name: "Renal Scan (DTPA / DMSA / MAG3)", description: "Renal", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-003", specifications: ["Renal", "Radiotracer"] },
  { id: "nuclear-myocardial-perfusion-mpi-muga", name: "Myocardial Perfusion (MPI / MUGA)", description: "Cardiac", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-004", specifications: ["Cardiac", "Radiotracer"] },
  { id: "nuclear-pet-ct-whole-body-oncology", name: "PET-CT (Whole body - oncology)", description: "Whole body", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-005", specifications: ["Whole body", "FDG"] },
  { id: "nuclear-pet-ct-brain", name: "PET-CT Brain", description: "Head", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-006", specifications: ["Head", "FDG"] },
  { id: "nuclear-hida-scan-hepatobiliary", name: "HIDA Scan (hepatobiliary)", description: "HBP", modality: "Nuclear Medicine", category: "Nuclear Medicine & PET", code: "NUCLEAR-007", specifications: ["HBP", "Radiotracer"] },
  { id: "bone-dexa-bmd-bone-mineral-density", name: "DEXA / BMD (Bone Mineral Density)", description: "Spine + Hip", modality: "Bone Densitometry", category: "Bone Densitometry & Others", code: "BONE-001", specifications: ["Spine + Hip"] },
  { id: "bone-opg-orthopantomogram-dental", name: "OPG (Orthopantomogram - dental)", description: "Dental/Jaw", modality: "Bone Densitometry", category: "Bone Densitometry & Others", code: "BONE-002", specifications: ["Dental/Jaw"] },
  { id: "bone-cephalogram-lateral-ortho", name: "Cephalogram (Lateral - ortho)", description: "Head/Face", modality: "Bone Densitometry", category: "Bone Densitometry & Others", code: "BONE-003", specifications: ["Head/Face"] },
  { id: "bone-digital-mammography-guided-screening-add-on", name: "Digital Mammography-guided / Screening add-on", description: "Breast", modality: "Bone Densitometry", category: "Bone Densitometry & Others", code: "BONE-004", specifications: ["Breast"] },
];

export const radiologyTestGroups: RadiologyGroup[] = [
  { id: "ct-scan", name: "CT Scan", modality: "CT", tests: radiologyTestList.filter((test) => test.category === "CT Scan").map((test) => test.id) },
  { id: "ultrasound", name: "Ultrasound", modality: "Ultrasound", tests: radiologyTestList.filter((test) => test.category === "Ultrasound").map((test) => test.id) },
  { id: "mri", name: "MRI", modality: "MRI", tests: radiologyTestList.filter((test) => test.category === "MRI").map((test) => test.id) },
  { id: "xray", name: "X-Ray", modality: "X-Ray", tests: radiologyTestList.filter((test) => test.category === "X-Ray").map((test) => test.id) },
  { id: "mammography", name: "Mammography", modality: "Mammography", tests: radiologyTestList.filter((test) => test.category === "Mammography").map((test) => test.id) },
  { id: "fluoroscopy-contrast", name: "Fluoroscopy & Contrast Studies", modality: "Fluoroscopy", tests: radiologyTestList.filter((test) => test.category === "Fluoroscopy & Contrast Studies").map((test) => test.id) },
  { id: "interventional-radiology", name: "Interventional Radiology", modality: "Interventional Radiology", tests: radiologyTestList.filter((test) => test.category === "Interventional Radiology").map((test) => test.id) },
  { id: "nuclear-medicine-pet", name: "Nuclear Medicine & PET", modality: "Nuclear Medicine", tests: radiologyTestList.filter((test) => test.category === "Nuclear Medicine & PET").map((test) => test.id) },
  { id: "bone-densitometry-others", name: "Bone Densitometry & Others", modality: "Bone Densitometry", tests: radiologyTestList.filter((test) => test.category === "Bone Densitometry & Others").map((test) => test.id) },
];

export const radiologyPriorities: RadiologyPriority[] = ["Routine", "Urgent", "STAT", "ASAP"];

const today = new Date();
const orderDateTime = `${today.toISOString().slice(0, 10)} ${today.toTimeString().slice(0, 5)}`;

export const radiologySummaryRows: RadiologySummaryRow[] = [
  { id: "rad-xray", selectedTests: "Chest X-Ray", loincCode: "71045", category: "X-Ray", specification: "PA View", priority: "Routine", status: "Ordered", orderDateTime },
  { id: "rad-ct", selectedTests: "CT Brain", loincCode: "24725-4", category: "CT Scan", specification: "Without Contrast", priority: "Urgent", status: "Scheduled", orderDateTime },
  { id: "rad-usg", selectedTests: "USG Abdomen", loincCode: "41806-1", category: "Ultrasound", specification: "Whole Abdomen", priority: "STAT", status: "Completed", orderDateTime },
];

export const radiologyResultBlocks: RadiologyResultBlock[] = [
  {
    id: "rad-xray-result",
    selectedTests: "Chest X-Ray",
    loincCode: "71045",
    category: "X-Ray",
    specification: "PA View",
    priority: "Routine",
    reportDate: "14/05/2021",
    radiologist: "Dr. Kavita Rao",
    findings: "Lungs are clear. No focal consolidation or pleural effusion.",
    impression: "Normal chest radiograph.",
    rows: [
      { parameter: "Lungs", result: "Clear", unit: "-", referenceRange: "Clear" },
      { parameter: "Cardiomediastinal silhouette", result: "Normal", unit: "-", referenceRange: "Normal" },
    ],
  },
  {
    id: "rad-ct-result",
    selectedTests: "CT Brain",
    loincCode: "24725-4",
    category: "CT Scan",
    specification: "Without Contrast",
    priority: "Urgent",
    reportDate: "14/05/2021",
    radiologist: "Dr. Kavita Rao",
    findings: "No acute intracranial hemorrhage or midline shift.",
    impression: "No acute CT brain abnormality.",
    rows: [
      { parameter: "Hemorrhage", result: "Absent", unit: "-", referenceRange: "Absent" },
      { parameter: "Midline shift", result: "Absent", unit: "mm", referenceRange: "0" },
    ],
  },
];
